/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as AdminElectionPartiesIndexRouteImport } from './routes/_admin/election-parties/index'
import { Route as AdminElectionPartiesAddRouteImport } from './routes/_admin/election-parties/add'
import { Route as AdminElectionPartiesPartyIdRouteImport } from './routes/_admin/election-parties/$partyId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AdminElectionPartiesIndexRoute =
  AdminElectionPartiesIndexRouteImport.update({
    id: '/election-parties/',
    path: '/election-parties/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminElectionPartiesAddRoute = AdminElectionPartiesAddRouteImport.update({
  id: '/election-parties/add',
  path: '/election-parties/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionPartiesPartyIdRoute =
  AdminElectionPartiesPartyIdRouteImport.update({
    id: '/election-parties/$partyId',
    path: '/election-parties/$partyId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/test': typeof TestIndexRoute
  '/election-parties/$partyId': typeof AdminElectionPartiesPartyIdRoute
  '/election-parties/add': typeof AdminElectionPartiesAddRoute
  '/election-parties': typeof AdminElectionPartiesIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/test': typeof TestIndexRoute
  '/election-parties/$partyId': typeof AdminElectionPartiesPartyIdRoute
  '/election-parties/add': typeof AdminElectionPartiesAddRoute
  '/election-parties': typeof AdminElectionPartiesIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/contact/': typeof ContactIndexRoute
  '/test/': typeof TestIndexRoute
  '/_admin/election-parties/$partyId': typeof AdminElectionPartiesPartyIdRoute
  '/_admin/election-parties/add': typeof AdminElectionPartiesAddRoute
  '/_admin/election-parties/': typeof AdminElectionPartiesIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/test'
    | '/election-parties/$partyId'
    | '/election-parties/add'
    | '/election-parties'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/test'
    | '/election-parties/$partyId'
    | '/election-parties/add'
    | '/election-parties'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/contact/'
    | '/test/'
    | '/_admin/election-parties/$partyId'
    | '/_admin/election-parties/add'
    | '/_admin/election-parties/'
    | '/_protected/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ContactIndexRoute: typeof ContactIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_admin/election-parties/': {
      id: '/_admin/election-parties/'
      path: '/election-parties'
      fullPath: '/election-parties'
      preLoaderRoute: typeof AdminElectionPartiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/election-parties/add': {
      id: '/_admin/election-parties/add'
      path: '/election-parties/add'
      fullPath: '/election-parties/add'
      preLoaderRoute: typeof AdminElectionPartiesAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/election-parties/$partyId': {
      id: '/_admin/election-parties/$partyId'
      path: '/election-parties/$partyId'
      fullPath: '/election-parties/$partyId'
      preLoaderRoute: typeof AdminElectionPartiesPartyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminElectionPartiesPartyIdRoute: typeof AdminElectionPartiesPartyIdRoute
  AdminElectionPartiesAddRoute: typeof AdminElectionPartiesAddRoute
  AdminElectionPartiesIndexRoute: typeof AdminElectionPartiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminElectionPartiesPartyIdRoute: AdminElectionPartiesPartyIdRoute,
  AdminElectionPartiesAddRoute: AdminElectionPartiesAddRoute,
  AdminElectionPartiesIndexRoute: AdminElectionPartiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ContactIndexRoute: ContactIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
